services:
  postgres:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build: ./fastapi
    container_name: fastapi_app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://pguser:pgpassword@db:5433/pgdb
    volumes:
      - ./fastapi/app:/app/app
volumes:
  pgdata:



